<?php
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostGrid.php';
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostList.php';

return apply_filters('zolo_blocks_list_data', [
    'container'          => [
        'name'       => 'container',
        'title'      => __('Container', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://zoloblocks.com',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'accordion'          => [
        'name'       => 'accordion',
        'title'      => __('Accordion', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/acordion',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'accordion-child'    => [
        'name'       => 'accordion-child',
        'title'      => __('Accordion Child', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_child'   => true,
    ],
    'advanced-button'    => [
        'name'       => 'advanced-button',
        'title'      => __('Advanced Button', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/adavanced-button',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-heading'   => [
        'name'       => 'advanced-heading',
        'title'      => __('Advanced Heading', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/adavanced-heading',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-icon-box'  => [
        'name'       => 'advanced-icon-box',
        'title'      => __('Advanced Icon Box', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/advanced-icon-box',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-image'     => [
        'name'       => 'advanced-image',
        'title'      => __('Advanced Image', 'zoloblocks'),
        'categories' => ['gallery'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/adavanced-image',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-search'    => [
        'name'       => 'advanced-search',
        'title'      => __('Advanced Search', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/adavanced-search',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'brand-child'        => [
        'name'       => 'brand-child',
        'title'      => __('Brand Child', 'zoloblocks'),
        'categories' => ['list'],
        'status'     => true,
        'is_child'   => true,
    ],
    'brand-grid'         => [
        'name'       => 'brand-grid',
        'title'      => __('Brand Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/brand-grid',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'business-hour'      => [
        'name'       => 'business-hour',
        'title'      => __('Business Hour', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/business-hour',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'charts'             => [
        'name'       => 'charts',
        'title'      => __('Charts', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/charts',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'countdown'          => [
        'name'       => 'countdown',
        'title'      => __('Countdown', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/countdown',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'counter'            => [
        'name'       => 'counter',
        'title'      => __('Counter', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/counter',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'cta'                => [
        'name'       => 'cta',
        'title'      => __('CTA', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/cta',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'email'              => [
        'name'       => 'email',
        'title'      => __('Email', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_child'   => true,
    ],
    'fancy-list'         => [
        'name'       => 'fancy-list',
        'title'      => __('Fancy List', 'zoloblocks'),
        'categories' => ['list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/fancy-list',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'fancy-list-child'   => [
        'name'       => 'fancy-list-child',
        'title'      => __('Fancy List Child', 'zoloblocks'),
        'categories' => ['list'],
        'status'     => true,
        'is_child'   => true,
    ],
    'flipbox'            => [
        'name'       => 'flipbox',
        'title'      => __('Flipbox', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/flipbox',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'form'               => [
        'name'       => 'form',
        'title'      => __('Form', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/form',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'google-map'         => [
        'name'       => 'google-map',
        'title'      => __('Google Map', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/google-map',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'icon' => [
        'name'       => 'icon',
        'title'      => __('Icon', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/icon',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'image-compare'      => [
        'name'       => 'image-compare',
        'title'      => __('Image Compare', 'zoloblocks'),
        'categories' => ['gallery'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/image-compare',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'image-gallery'      => [
        'name'       => 'image-gallery',
        'title'      => __('Image Gallery', 'zoloblocks'),
        'categories' => ['gallery'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/image-gallery',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'list'               => [
        'name'       => 'list',
        'title'      => __('List', 'zoloblocks'),
        'categories' => ['list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/list',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'newsletter'         => [
        'name'       => 'newsletter',
        'title'      => __('Newsletter', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/newsletter',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'notice'             => [
        'name'       => 'notice',
        'title'      => __('Notice', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/notice',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'popup-builder'      => [
        'name'       => 'popup-builder',
        'title'      => __('Popup Builder', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/popup-builder',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-carousel'      => [
        'name'       => 'post-carousel',
        'class'      => '\Zolo\Blocks\PostCarousel',
        'title'      => __('Post Carousel', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-carousel',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-grid'          => [
        'name'       => 'post-grid',
        'class'      => '\Zolo\Blocks\PostGrid',
        'title'      => __('Post Grid', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-grid',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-list'          => [
        'name'       => 'post-list',
        'class'      => '\Zolo\Blocks\PostList',
        'title'      => __('Post List', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-list',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'pricing-table'      => [
        'name'       => 'pricing-table',
        'title'      => __('Pricing Table', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/pricing-table',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'profile-card'       => [
        'name'       => 'profile-card',
        'title'      => __('Profile Card', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/profile-card',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'progress-bar'       => [
        'name'       => 'progress-bar',
        'title'      => __('Progress Bar', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/progress-bar',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'progress-bar-child' => [
        'name'       => 'progress-bar-child',
        'title'      => __('Progress Bar Child', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_child'   => true,
    ],
    'progress-pie'       => [
        'name'       => 'progress-pie',
        'title'      => __('Progress Pie', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/progress-pie',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'qrcode'             => [
        'name'       => 'qrcode',
        'title'      => __('QR Code', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/qrcode',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'review'             => [
        'name'       => 'review',
        'title'      => __('Review', 'zoloblocks'),
        'categories' => ['review'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/review',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'review-carousel'    => [
        'name'       => 'review-carousel',
        'title'      => __('Review Carousel', 'zoloblocks'),
        'categories' => ['review', 'slider'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/reviw-carousel',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'review-child'       => [
        'name'       => 'review-child',
        'title'      => __('Review Child', 'zoloblocks'),
        'categories' => ['review'],
        'status'     => true,
        'is_child'   => true,
    ],
    'review-grid'        => [
        'name'       => 'review-grid',
        'title'      => __('Review Grid', 'zoloblocks'),
        'categories' => ['review', 'list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/reviw-grid',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'slide'              => [
        'name'       => 'slide',
        'title'      => __('Slide', 'zoloblocks'),
        'categories' => ['slider'],
        'status'     => true,
        'is_child'   => true,
    ],
    'slider'             => [
        'name'       => 'slider',
        'title'      => __('Slider', 'zoloblocks'),
        'categories' => ['slider'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/slider',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'social-links'       => [
        'name'       => 'social-links',
        'title'      => __('Social Links', 'zoloblocks'),
        'categories' => ['social'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/social-links',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'social-share'       => [
        'name'       => 'social-share',
        'title'      => __('Social Share', 'zoloblocks'),
        'categories' => ['social'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/social-share',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'star-rating'        => [
        'name'       => 'star-rating',
        'title'      => __('Star Rating', 'zoloblocks'),
        'categories' => ['review'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/star-rating',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'tab'                => [
        'name'       => 'tab',
        'title'      => __('Tab', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_child'   => true,
    ],
    'tabs'               => [
        'name'       => 'tabs',
        'title'      => __('Tabs', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/tabs',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'team-grid'          => [
        'name'       => 'team-grid',
        'title'      => __('Team Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/team-grid',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'team-child'     => [
        'name'       => 'team-child',
        'title'      => __('Team Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status'     => true,
        'is_child'   => true,
    ],
    'text-field'         => [
        'name'       => 'text-field',
        'title'      => __('Text Field', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_child'   => true,
    ],
    'text-path'          => [
        'name'       => 'text-path',
        'title'      => __('Text Path', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/text-path',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'textarea'           => [
        'name'       => 'textarea',
        'title'      => __('Textarea', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_child'   => true,
    ],
    'post-category'      => [
        'name'       => 'post-category',
        'class'      => '\Zolo\Blocks\PostCategory',
        'title'      => __('Post Category', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-category',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-timeline'      => [
        'name'       => 'post-timeline',
        'class'      => '\Zolo\Blocks\PostTimeline',
        'title'      => __('Post Timeline', 'zoloblocks'),
        'categories' => ['list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-timeline',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'tag-cloud'          => [
        'name'       => 'tag-cloud',
        'class'      => '\Zolo\Blocks\TagCloud',
        'title'      => __('Tag Cloud', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/tag-cloud',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-list'          => [
        'name'       => 'post-list',
        'class'      => '\Zolo\Blocks\PostList',
        'title'      => __('Post List', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-list',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'lightbox'           => [
        'name'       => 'lightbox',
        'title'      => __('Lightbox', 'zoloblocks'),
        'categories' => ['gallery'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/lightbox',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'author'             => [
        'name'       => 'author',
        'class'      => '\Zolo\Blocks\Author',
        'title'      => __('Author', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/author',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'social-count'       => [
        'name'       => 'social-count',
        'title'      => __('Social Count', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/social-count',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'social-count-child' => [
        'name'       => 'social-count-child',
        'title'      => __('Social Count Child', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_child'   => true,
    ],
    'post-comments'      => [
        'name'       => 'post-comments',
        'class'      => '\Zolo\Blocks\PostComments',
        'title'      => __('Post Comments', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-comments',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'breadcrumbs'        => [
        'name'       => 'breadcrumbs',
        'class'      => '\Zolo\Blocks\BreadcrumbsBlock',
        'title'      => __('Breadcrumbs', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/breadcrumbs',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-title'        => [
        'name'       => 'post-title',
        'class'      => '\Zolo\Blocks\PostTitle',
        'title'      => __('Post Title', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-title',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ]
]);
