<?php
return apply_filters('zolo_extensions', [
    'cursors'          => [
        'name'   => 'cursors',
        'title'  => __('Cursors Animation', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'floating'          => [
        'name'   => 'floating',
        'title'  => __('Floating Animation', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'entrance'          => [
        'name'   => 'entrance',
        'title'  => __('Entrance Animation', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'sticky'          => [
        'name'   => 'sticky',
        'title'  => __('Sticky Position', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'parallax'          => [
        'name'   => 'parallax',
        'title'  => __('Parallax Effect', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'particles'          => [
        'name'   => 'particles',
        'title'  => __('Particles Animation', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'tilt'          => [
        'name'   => 'tilt',
        'title'  => __('Mouse Tilt', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'smooth-scroller'          => [
        'name'   => 'smooth-scroller',
        'title'  => __('Smooth Scroller', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'css-filters'          => [
        'name'   => 'css-filters',
        'title'  => __('CSS Filters', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'backdrop-filters'          => [
        'name'   => 'backdrop-filters',
        'title'  => __('Backdrop Filters', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'background-parallax'          => [
        'name'   => 'background-parallax',
        'title'  => __('Background Parallax', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'released' => false,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'export-pattern'          => [
        'name'   => 'export-pattern',
        'title'  => __('Export Pattern', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'import-pattern'          => [
        'name'   => 'import-pattern',
        'title'  => __('Import Pattern', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'shape-divider'          => [
        'name'   => 'shape-divider',
        'title'  => __('Shape Divider', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/acordion',
        'video'  => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'dynamic-content'          => [
        'name'     => 'dynamic-content',
        'title'    => __('Dynamic Content', 'zoloblocks'),
        'status'   => false,
        'is_pro'   => true,
        'released' => false,
        'demo'     => 'https://demo.zoloblocks.com/acordion',
        'video'    => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ]
]);
